/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArgSettings: typeof import('./src/components/ArgSettings.vue')['default']
    ArgsSettings: typeof import('./src/components/DevSettings.vue')['default']
    ArgumentSettings: typeof import('./src/components/ArgumentSettings.vue')['default']
    ButtonSwitch: typeof import('./src/components/ButtonSwitch.vue')['default']
    CameraView: typeof import('./src/components/CameraView.vue')['default']
    DevArgsPopuyp: typeof import('./src/components/DevArgsPopuyp.vue')['default']
    DeviceInfo: typeof import('./src/components/dashboard/DeviceInfo.vue')['default']
    DevSettings: typeof import('./src/components/footer/DevSettings.vue')['default']
    DevSwitch: typeof import('./src/components/footer/DevSwitch.vue')['default']
    DevSwitchGroup: typeof import('./src/components/footer/DevSwitchGroup.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    List: typeof import('./src/components/dashboard/List.vue')['default']
    ListItem: typeof import('./src/components/dashboard/ListItem.vue')['default']
    ParamInfo: typeof import('./src/components/dashboard/ParamInfo.vue')['default']
    ParamsInfo: typeof import('./src/components/dashboard/ParamsInfo.vue')['default']
    PopupSettings: typeof import('./src/components/PopupSettings.vue')['default']
    SensorInfo: typeof import('./src/components/dashboard/SensorInfo.vue')['default']
    SensorInfoList: typeof import('./src/components/dashboard/SensorInfoList.vue')['default']
    TwoStateButton: typeof import('./src/components/TwoStateButton.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
