/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ButtonSwitch: typeof import('./src/components/ButtonSwitch.vue')['default']
    Controller: typeof import('./src/components/Controller.vue')['default']
    Dashboard: typeof import('./src/components/Dashboard.vue')['default']
    DevSettings: typeof import('./src/components/DevSettings.vue')['default']
    DevSwitch: typeof import('./src/components/DevSwitch.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Header: typeof import('./src/components/Header.vue')['default']
    Ipv4Input: typeof import('./src/components/Ipv4Input.vue')['default']
    NumberIcon: typeof import('./src/components/NumberIcon.vue')['default']
  }
}
